jenkinsci/cloudbees-jenkins-advisor-plugin

src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java

[JARVIS-111](https://cloudbees.atlassian.net/browse/JARVIS-111)
Building on PR4: added the translation on the doTestConnection method.  Now testing the connection works no matter what the state is, and the password is hidden with Secret.
@reviewbybees

[JARVIS-111] Change to secret from String

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/Reminder.java

Making doAct protected broke this. The method needs to be public.
I also removed StaplerRequest from the method as its not used.
@kwhetstone

JARVIS-115 - 404 on "Connect Now" admin monitor link.

---

pom.xml
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java
src/test/resources/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientConfig.properties

JARVIS-107 - BundleUpload tests

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/Reminder.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/ReminderTest.java

Also stripped out the piece in Reminder about checking for the licensing screens since this no longer nags with the dropdown.
@reviewbybees

Tests for Reminder

---

pom.xml
src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClient.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/model/AccountCredentials.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientTest.java

JARVIS-101 - Use Jenkins async-http-client plugin

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java

[JARVIS-138](https://cloudbees.atlassian.net/browse/JARVIS-138)
Added tests for the excluded components from the global configuration page.
@reviewbybees

[JARVIS-138] Add tests for excluded components

---

src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java

Basically add a UI check and a test for more of a mix of components so at least we know that the configuration will be displayed properly to the user.  Pending review.
@reviewbybees

Add UI checks to AdvisorGlobalConfg test

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java

Output the messages to the task log file so we have a good idea of what's going on within each run of the task.
@reviewbybees

Write messages to task log file

---

src/test/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientTest.java

Added a test when the user didn't enter the correct credentials.  An error is thrown explaining that there was "No Authorization". 
@reviewbybees

Add test for authentication failure.

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java

Remove deprecated usage

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java

Addressing the issue brought up in  jenkins-infra/deprecated-usage-in-plugins#7
Pending review @Evildethow

Remove dependency on SystemProperties

---

README.md
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java

Will need to update the wiki as well

JARVIS-223 - Change upload recurrence period from minutes to hours

---

pom.xml
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClient.java

[JENKINS_48145](https://issues.jenkins-ci.org/browse/JENKINS-48145)
Hotfix for new installs of the plugin.  /cc @Evildethow

[JENKINS-48145] Hotfix

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java

https://issues.jenkins-ci.org/browse/JENKINS-59454

JENKINS-59454 (OSS-2776) - Increase Advisor bundle generation delay to 30mins

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/resources/lib/advisor/validateOnLoad.jelly

https://issues.jenkins-ci.org/browse/JENKINS-59629

JENKINS-59629 (OSS-2778) - Not validating the TOS is confusing

---

README.md
pom.xml
src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/help-nagDisabled.html
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly
src/main/resources/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitor/message.properties
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Messages.properties
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Reminder/message.properties
src/main/resources/lib/advisor/validateOnLoad.jelly
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitorTest.java

[https://issues.jenkins-ci.org/browse/JENKINS-59613](https://issues.jenkins-ci.org/browse/JENKINS-59613)

[JENKINS-59613] Rename all occurrences of "CloudBees Jenkins Advisor" by "Jenkins Health Advisor by CloudBees"

---

pom.xml
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitor.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/Reminder.java
src/main/resources/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitor/message.jelly
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Reminder/message.jelly

https://issues.jenkins-ci.org/browse/JENKINS-59644

[JENKINS-59644] Bump the Jenkins core requirement to 2.138.4 ( + cleanup )

---

pom.xml
src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/Reminder.java
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/help-nagDisabled.html
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Messages.properties
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Reminder/message.jelly
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Reminder/message.properties
src/main/resources/index.jelly
src/main/resources/lib/advisor/validateOnLoad.jelly
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java

Ref: https://issues.jenkins-ci.org/browse/JENKINS-59648
Few screenshots

[JENKINS-59648] UX improvements

---

pom.xml

https://issues.jenkins-ci.org/browse/JENKINS-59647

[JENKINS-56647] [task] Upgrade support-core dependency to 2.62

---

pom.xml

Your Wiki page is so cool that I did not even recognize Wiki :P 
FTR: https://groups.google.com/forum/#!topic/jenkinsci-dev/VSdfVMDIW-A
@reviewbybees

Use GitHub as a source of the plugin documentation

---

README.md

subj. 
It does not cause any user impact except some better analytics on the target websites.

Add a marketing campaign metadata to the "Supported by CloudBees badge" and other resources

---

README.md
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Messages.properties
src/main/resources/lib/advisor/validateOnLoad.jelly

More efforts to use only "Jenkins Health Advisor by CloudBees"

[fix] Remove Trademark violations

---

src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly
src/main/resources/lib/advisor/validateOnLoad.jelly

@oleg-nenashev does it makes sense to do it from the links available in the plugin too ?

Add a marketing campaign metadata in the links displayed in the configuration page

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorRootConfigurator.java
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly
src/main/resources/lib/advisor/validateOnLoad.jelly
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java

+ Improve validations
+ Improve UI with Bootstrap

[JENKINS-59697] Add an Apply button

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorRootConfigurator.java
src/main/resources/lib/advisor/validateOnLoad.jelly

During a demo I spotted a couple of small improvements:
- A logger that was not actually used.
- A text that could be improved (I think).

Small improvements I just oversaw during a demo.

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java

Requires Jenkins core 2.226+
Ref:
* https://jenkins.io/changelog/#v2.226
* https://github.com/jenkinsci/jenkins/pull/4546

Name of the category for this management link

---

pom.xml

Alternative to #77, pending https://github.com/jenkinsci/bom/pull/294.

Work around problem in io.jenkins.configuration-as-code:test-harness

---

src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly

https://issues.jenkins-ci.org/browse/JENKINS-63814

JENKINS-63814 New Terms of Service URL

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailValidator.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorRootConfiguratorTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailValidatorTest.java

[JENKINS-65230] Remove the regexp check on emails

---

README.md
pom.xml
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/help-acceptToS.html
src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Messages.properties
src/main/resources/com/cloudbees/jenkins/plugins/advisor/Reminder/message.properties
src/main/resources/index.jelly

[JENKINS-65435] Remove the usage of the master term

---

pom.xml

2.222.4 was released ~ a year ago: 2020-05-24
Bump done in Support Core [v2.73](https://github.com/jenkinsci/support-core-plugin/releases/tag/support-core-2.73) and required by #97 
- ~[ ] Link to relevant issues in GitHub or Jira~
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~

Bump jenkins version requirement from 2.204.6 to 2.222.4

---

.github/release-drafter.yml

Fix release name template for Release Drafter

---

src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/model/Recipient.java

Ensure authorization is checked on check email endpoints

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml

- [s] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [s] Ensure that the pull request title represents the desired changelog entry
- [s] Please describe what you did

[chore] enable incrementals

---

pom.xml
src/main/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUpload.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitor.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/Reminder.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorRootConfigurator.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClient.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientConfig.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/HttpUrlConnectionFactory.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/MultipartConnection.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/PluginHelper.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/dto/UserInfo.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/model/ClientResponse.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/model/ClientUploadRequest.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/client/model/Recipient.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailUtil.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailValidator.java
src/main/java/com/cloudbees/jenkins/plugins/advisor/utils/FileHelper.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitorTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/ReminderTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorJCasCompatibilityTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorRootConfiguratorTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientConfigTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/PluginHelperTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailUtilTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailValidatorTest.java

Activate the spotless formatting, inherited from the Jenkins project.

[chore] Activate spotless

---

src/main/resources/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientConfig.properties

`advisor.cloudbees.com`  should probably be used. It's been set up for a while. I guess we never updated this. Maybe it requires bigger communication and more planning..
```[tasklist]
```

[chore] Switch from legacy DNS to correct one

---

pom.xml
src/test/java/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfigurationTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadMonitorTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/BundleUploadTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/ReminderTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorJCasCompatibilityTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/casc/AdvisorRootConfiguratorTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientConfigTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/AdvisorClientTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/client/PluginHelperTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailUtilTest.java
src/test/java/com/cloudbees/jenkins/plugins/advisor/utils/EmailValidatorTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5
